{
 "title": "Dashboard suivi de l'api RAG FAQ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Statut de l'api",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nombre de requêtes total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "faq_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temps d'inférence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(faq_response_time_seconds_sum[5m]) / rate(faq_response_time_seconds_count[5m])",
     "legendFormat": "moyenne"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(faq_response_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(faq_response_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Score de confiance moyen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(faq_confidence_score_sum[5m])) / avg(rate(faq_confidence_score_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requête par secondes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(faq_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution des scores de confiances",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 13, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "sum(faq_confidence_score_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historique du statut de l'api",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"fastapi_app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}