from fastapi import APIRouter, HTTPException, Depends
from typing import List

from src.models import QuestionRequest, AnswerResponse, FAQ
from src.services.rag_service import RAGService
from src.services.data_loader import load_faq_data

router = APIRouter()

_rag_service_instance = None

def get_rag_service():
    global _rag_service_instance
    if _rag_service_instance is None:
        _rag_service_instance = RAGService()
    return _rag_service_instance

def get_faq_df():
    return load_faq_data()



@router.post("/answer", response_model=AnswerResponse, summary="Get an answer using the recommended RAG strategy")
async def get_answer(
    request: QuestionRequest,
    rag_service: RAGService = Depends(get_rag_service)
):
    """
    Receives a question and returns an answer generated by the RAG strategy.
    """
    try:
        result = rag_service.answer_question(request.question)
        return AnswerResponse(**result)
    except Exception as e:
        # TODO: improve error handling
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/faq", response_model=List[FAQ], summary="List all FAQs")
async def list_faqs(faq_df = Depends(get_faq_df)):
    """
    Returns a list of all FAQ items from the knowledge base.
    """
    if faq_df.empty:
        return []
    faqs = [FAQ(**record) for record in faq_df.to_dict(orient='records')]
    return faqs

@router.get("/faq/{faq_id}", response_model=FAQ, summary="Get a specific FAQ by ID")
async def get_faq_by_id(faq_id: str, faq_df = Depends(get_faq_df)):
    """
    Returns a single FAQ item by its unique ID.
    """
    if faq_df.empty:
        raise HTTPException(status_code=404, detail="FAQ data not available.")
        
    faq_item = faq_df[faq_df['id'] == faq_id]
    
    if faq_item.empty:
        raise HTTPException(status_code=404, detail=f"FAQ with id '{faq_id}' not found.")
        
    return FAQ(**faq_item.to_dict(orient='records')[0])
